name = "campervan-mcp-server"
main = "src/index.ts"
compatibility_date = "2026-07-01"

# D1 Relational DB Binding
[[d1_databases]]
binding = "DB"
database_name = "van_specs_db"
database_id = "2aa73cfb-cf41-4ab3-b614-b0cf1eb7ec0c"
migrations_dir = "d1/migrations"

# Vectorize Binding
[[vectorize]]
binding = "VECTOR_INDEX"
index_name = "van_manuals_index"

[vars]
ENVIRONMENT = "production"
